# Generated by Django 4.2 for the extended Cat profile.

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("cats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="color",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="cat",
            name="temperament",
            field=models.CharField(default="спокойный", max_length=80),
        ),
        migrations.AddField(
            model_name="cat",
            name="favorite_toy",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="cat",
            name="vaccinated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cat",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cat",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cat",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
