# Generated by Django 4.2 for public showcase fields.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cats", "0002_cat_extended_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Ищет дом"),
                    ("reserved", "Забронирован"),
                    ("stays", "Остаётся в питомнике"),
                ],
                default="available",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="cat",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cat",
            name="show_in_showcase",
            field=models.BooleanField(default=True),
        ),
    ]
