# Generated by Django 4.2 for care and behavior fields.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cats", "0004_cat_photo_catlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="character_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cat",
            name="food",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="cat",
            name="litter_trained",
            field=models.BooleanField(default=True),
        ),
    ]
